#+TITLE: My Emacs Config
#+AUTHOR: Daniel Laguna
#+EMAIL: labellson@gmail.com

* Introduction
The idea of generating an emacs config file using =org-mode= is taken from
[[https://youtu.be/SzA2YODtgK4][Harry Schwartz's talk about org-mode]]. When Emacs starts, all the elisp code
blocks from this file are parsed and used to generate the config. This is done
through [[http://orgmode.org/worg/org-contrib/babel/][org-babel]]. =Babel= is Org-mode's ability to execute source code within
=org-mode= documents.

To use this config file, you need to evaluate this file on startup. This can be
done writing this line ~(org-babel-load-file "~/.my-emacs/README.org")~ into
your [[file:init.el][init.el]].

*NOTE*: This file assumes that your =org-mode= config file is located into
=~/.my-emacs/README.org=.

* Basic Emacs Setup
** My information
Relevant personal information that Emacs needs.

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Daniel Laguna"
    user-mail-address "labellson@gmail.com"
    calendar-latitude 40.33
    calendar-longitude -3.76
    calendar-location-name "Madrid, Spain")
#+END_SRC

** Adding MELPA 
MELPA is the main package repository for Emacs. There are more repositories and
you are able to add more than one. *But make sure you are using HTTPS!!*.

#+BEGIN_SRC emacs-lisp
;; Set up the package manager and repositories
(require 'package)

(add-to-list 'package-archives '("MELPA" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/"))

(setq package-enable-at-startup nil)
(package-initialize)
#+END_SRC

** TAB
=<TAB>= key run indentation in most of the major mode. Sometimes, I want to
=<TAB>= behaves as inserting a tab character. I can do this typing =C-q-<TAB>=
but I don't like the default widht. So...

#+BEGIN_SRC emacs-lisp
(setq-default tab-width 4)
#+END_SRC

* Emacs GUI
** =delight= to manage mode names in the mode-line
This package let us rename or hide mode names in the mode-line. It's fully
compatible with =use-package=.

#+BEGIN_SRC emacs-lisp
(use-package delight
  :ensure t
  :demand t)
#+END_SRC

Emacs provides some minor modes that I want to hide as well.

#+BEGIN_SRC emacs-lisp
(use-package emacs
  :delight
  (auto-revert-mode)
  (visual-line-mode))
#+END_SRC

* Programming Modes
** =company=
[[http://company-mode.github.io/][Company]] is a text completion framework for Emacs. The name stands for "complete
anything". It uses pluggable back-ends and front-ends to retrieve and display
completion candidates.

Add =company-tng-frontend= if you like YCM Vim completion :P

#+BEGIN_SRC emacs-lisp
(use-package company
  :delight
  :ensure t
  :config
    (setq company-tooltip-align-annotations t)
    (eval-after-load 'company
      '(progn
        (add-hook 'prog-mode-hook 'company-mode)
        (add-to-list 'company-frontends 'company-tng-frontend)
        (define-key company-active-map (kbd "TAB") 'company-complete-common-or-cycle)
        (define-key company-active-map [tab] 'company-complete-common-or-cycle)
        (define-key company-active-map (kbd "S-TAB") 'company-select-previous)
        (define-key company-active-map (kbd "<backtab>") 'company-select-previous)
        
        (define-key company-mode-map (kbd "C-<SPC>") 'company-complete))))
#+END_SRC

With =company-flx= we add fuzzy matching to =company=. But it seems only work
with =company-capf= backend.

#+BEGIN_SRC emacs-lisp
(use-package company-flx
  :delight
  :ensure t
  :config
    (eval-after-load 'company
      (company-flx-mode +1)))
#+END_SRC
   
** C/C++
I've been using *NeoVim* with =YouCompleteMe= for C/C++ development. But, I
want to change my default text editor to emacs. So, this section sums up my
research on C/C++ related emacs packages. 

** =emacs-ycmd=
I've been testing =rtags= and =irony= modes, but I could not properly
configurate. But, I've seen there's a client for =ycmd= on emacs too.

=emacs-ycmd= is an emacs mode that takes care of managing a ycmd server and
fetching completions from that server for offer some IDE-like functionality for
C/C++.

In order to use this package the [[https://github.com/Valloric/ycmd][ycmd]] server must be compiled. For C/C++
completion: ~./build.py --clang-completion~.

#+BEGIN_SRC emacs-lisp
(use-package ycmd
  :ensure t
  :config

  (set-variable 'ycmd-server-command `("python3",
									   (file-truename "~/.ycmd/ycmd")))
  (set-variable 'ycmd-global-config (expand-file-name "~/.ycmd/.ycm_extra_conf.py"))

  (add-hook 'c++-mode-hook #'ycmd-mode)
  (add-hook 'ycmd-mode-hook 'ycmd-eldoc-setup))
#+END_SRC

To enable code completion with company install the backend.

#+BEGIN_SRC emacs-lisp
(use-package company-ycmd
  :ensure t
  :config

  (company-ycmd-setup)

  (eval-after-load 'company
	'(add-to-list 'company-backends 'company-ycmd)))
#+END_SRC

For live code checking =flycheck-ycmd= must be installed.

#+BEGIN_SRC emacs-lisp
(use-package flycheck-ycmd
  :ensure t
  :config

  (flycheck-ycmd-setup)

  (add-hook 'ycmd-mode-hook 'flycheck-ycmd-setup))
#+END_SRC

** Python
In order to use ipython as default interpreter set these lines below.

#+BEGIN_SRC emacs-lisp
(setq python-shell-interpreter "ipython"
       python-shell-interpreter-args "--simple-prompt -i")
#+END_SRC

I've set a global =tab-width= in basic emacs setup. But it seems not working in
=python-mode=.

#+BEGIN_SRC emacs-lisp
(add-hook 'python-mode-hook
      (lambda ()
        (setq tab-width 4)))
#+END_SRC

*** =anaconda-mode=
[[https://github.com/proofit404/anaconda-mode][Anaconda]] provides context code completion, jump to definitions, find references
and documentation view through =eldoc= for python mode. Its usage is very
simple and it integrates with =company-mode=.

#+BEGIN_SRC emacs-lisp
(use-package anaconda-mode
  :ensure t
  :delight
  :config
    (add-hook 'python-mode-hook 'anaconda-mode)
    (add-hook 'python-mode-hook 'anaconda-eldoc-mode))
#+END_SRC

**** Default Keybinding
| Keybinding | Description                    |
|------------+--------------------------------|
| C-M-i      | anaconda-mode-complete         |
| M-.        | anaconda-mode-find-definitions |
| M-,        | anaconda-mode-find-assignments |
| M-r        | anaconda-mode-find-references  |
| M-*        | anaconda-mode-go-back          |
| M-?        | anaconda-mode-show-doc         |
   
*** =company-anaconda=
This is a backend for =company-mode= that works with =anaconda-mode=. Necessary
if you want autocompletion.

#+BEGIN_SRC emacs-lisp
(use-package company-anaconda
  :ensure t
  :delight
  :config

    (eval-after-load "company"
      '(add-to-list 'company-backends '(company-anaconda :with company-capf))))
#+END_SRC

** Javascript
*** =js-2mode=
Better [[https://emacs.cafe/emacs/javascript/setup/2017/04/23/emacs-setup-javascript.html][Javascript mode]].

#+BEGIN_SRC emacs-lisp
(use-package js2-mode
  :ensure t
  :delight
  :config

  (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
  (add-hook 'js2-mode-hook #'js2-imenu-extras-mode))
#+END_SRC
** COMMENT =hideshow=
This minor mode provides selectively folding for code and comment
blocks. Blocks are defined per mayor mode. It cames pre-configured with default
mayor modes like =c-mode, c++mode..=

You can configure this minor mode and enable it in different mayor modes with
this config. This [[https://emacs.stackexchange.com/questions/2884/the-old-how-to-fold-xml-question][issue]] explains how to configure for =nxml-mode=.

#+BEGIN_SRC emacs-lisp
(use-package hideshow
  :ensure t
  :delight
  :bind ("C-c h" . hs-toggle-hiding)
  :config
  (add-to-list 'hs-special-modes-alist
             '(nxml-mode
               "<!--\\|<[^/>]*[^/]>"
               "-->\\|</[^/>]*[^/]>"

               "<!--"
			   nxml-forward-element
               nil))
)

(add-hook 'nxml-mode-hook 'hs-minor-mode)
(add-hook 'python-mode-hook 'hs-minor-mode)
#+END_SRC
* WIP
These source blocks needs to be documented.

#+BEGIN_SRC emacs-lisp


;; Install use-package if not installed
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))


;; Show Parenthesis Mode
(setq show-paren-delay 0)
(show-paren-mode 1)

;; Hide the toolbar and menubar
(tool-bar-mode -1)
(menu-bar-mode -1)

;; Don't create backups
(setq make-backup-files nil)

;; Disable scroll bar
(scroll-bar-mode -1)

;; Load packages
(use-package evil
  :ensure t
  :config
  (evil-mode 1)

  ;; Evil key bindings
  (define-key evil-motion-state-map "j" 'evil-next-visual-line)
  (define-key evil-motion-state-map "k" 'evil-previous-visual-line)

  (use-package evil-leader
    :ensure t
    :config
    (global-evil-leader-mode)

    (evil-leader/set-leader "<SPC>")
    (evil-leader/set-key
      "x" 'counsel-M-x
      "<SPC>" 'evil-search-highlight-persist-remove-all
	  "i" 'counsel-imenu))

  (use-package evil-search-highlight-persist
   :ensure t
   :config
   (global-evil-search-highlight-persist t)))

(use-package gruvbox-theme
  :ensure t)

; Smooth scrolling on file limits
(use-package smooth-scrolling
  :ensure t
  :config
  (smooth-scrolling-mode 1))

; SimpleClip Super+C Super+X Super+V
(use-package simpleclip
  :ensure t
  :config
  (simpleclip-mode 1))

(use-package fill-column-indicator
  :ensure t
  :config
  ;(fci-mode)           ;activate fill-column-indicator. use lambda hook
  (set-fill-column 80))

;; Wrap lines
(global-visual-line-mode 1)

;; Show margin line numbers
(use-package nlinum
  :ensure t
  :config

  ;(global-nlinum-mode t)

  (use-package nlinum-relative
    :ensure t
    :config
   ;; something else you want
    (nlinum-relative-setup-evil)
    (setq nlinum-relative-redisplay-delay 0)
    (add-hook 'prog-mode-hook 'nlinum-relative-mode)))

(use-package linum-off
  :ensure t
  ;(setq linum-disabled-modes-list ‘(eshell-mode wl-summary-mode compilation-mode))
)

;; Zsh Tab completion for minibuffer
(use-package zlc
  :ensure t
  :config
  (zlc-mode t))

;; Spell checker
(when (executable-find "hunspell")
  (setq-default ispell-program-name "hunspell")
  (setq ispell-dictionary "es_ES")
  (setq ispell-really-hunspell t))

;; Word Count
(use-package wc-mode
  :ensure t
  :config)

;; org-mode

;; Folding character
(setq org-ellipsis " \u2935")

;; Prettify latex symbols
(setq-default org-pretty-entities t)

(use-package org-ref
  :ensure t
  :config

  (setq org-src-preserve-indentation t)

  (setq org-latex-default-packages-alist
	(-remove-item
	 '("" "hyperref" nil)
	 org-latex-default-packages-alist))

  (add-to-list 'org-latex-default-packages-alist '("" "natbib" "") t)
  (add-to-list 'org-latex-default-packages-alist
	       '("linktocpage,pdfstartview=FitH,colorlinks,linkcolor=black,anchorcolor=black,citecolor=black,filecolor=blue,menucolor=black,urlcolor=blue"
		 "hyperref" nil)
	       t)

  (progn
    (setq org-ref-bibliography-notes "~/Drive/org/bibliography/notes.org"
          org-ref-default-bibliography '("~/Drive/org/bibliography/main.bib")
          org-ref-pdf-directory "~/Drive/org/bibliography/pdfs"
          org-latex-pdf-process
          '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
            "bibtex %b"
            "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
            "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f")))

  (setq bibtex-autokey-year-length 4
      bibtex-autokey-name-year-separator "-"
      bibtex-autokey-year-title-separator "-"
      bibtex-autokey-titleword-separator "-"
      bibtex-autokey-titlewords 2
      bibtex-autokey-titlewords-stretch 1
      bibtex-autokey-titleword-length 5))

(use-package org-autolist
  :ensure t
  :config (add-hook 'org-mode-hook (lambda () (org-autolist-mode))))

;; Set the agenda files
(setq org-agenda-files (list "~/Drive/org/agenda.org"))

(use-package org-bullets
  :ensure t)
  ;:config
  ;(progn
  ;  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
  ;  (setq org-bullets-bullet-list
  ;        '("\u25c9" "\u25ce" "\u25cb" "\u25cb" "\u25cb" "\u25cb"))))

;; Add these evil keybindings in Emacs mode
(evil-add-hjkl-bindings occur-mode-map 'emacs
  (kbd "/")       'evil-search-forward
  (kbd "n")       'evil-search-next
  (kbd "N")       'evil-search-previous
  (kbd "C-d")     'evil-scroll-down
  (kbd "C-u")     'evil-scroll-up
  (kbd "C-w C-w") 'other-window)

;; Keyboard maps
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+END_SRC

* Org-mode
** Enable =auto-fill-mode=
This conf enables 80 characters auto filling per line inside =org-mode=. I
believe that 80 character per line enhances the readability of a text file.

If you want a visual behaviour inside =emacs= instead into the raw text file
check [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]].

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'auto-fill-mode)
(setq-default fill-column 79)
#+END_SRC
** IEEE export
For class assignments and who-knows-what in the future, I was able to integrate
a IEEE Conference template in org-mode export via Latex. To use it, just
include the IEEEtran class in your org file. It has not been thoroughly tested,
but its headers, index, abstract and general aesthetic works perfectly out of
the box.

#+BEGIN_SRC emacs-lisp
(add-to-list 'org-latex-classes
             '("IEEEtran" "\\documentclass[11pt]{IEEEtran}"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
             t)
#+END_SRC

** Native =TAB= in source blocks
By default =TAB= keystroke doesn't indent in =org= source blocks. Typing
=C-q-<TAB>= I can force a native =TAB= but I prefer this option that makes
=TAB= work as if the keystroke was issued in the code’s major mode.

#+BEGIN_SRC emacs-lisp
(setq org-src-tab-acts-natively t)
#+END_SRC

** Open source blocks in the same window
When editing source code in an org source block, we can open a new buffer to
edit the code in its major mode. This option makes it use the same window
instead of popping a new one.

#+BEGIN_SRC emacs-lisp
(setq org-src-window-setup 'current-window)
#+END_SRC

** Use syntax highlight in source blocks
When writing source code on a block, if this variable is enabled it will use
the same syntax highlight as the mode supposed to deal with it.

#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
#+END_SRC

** Source syntax highlight in =latex= exports
Using =org-mode= =latex= export you can get syntax highlighting in pdf using
the =minted= package, wich uses =Python= =pygments= package. This snippet was
taken from [[http://joonro.github.io/blog/posts/org-mode-outputdir-minted-latex-export.html][Joon's Blog]]. [[https://github.com/gpoore/minted/issues/92][Issue]] ~cache=false~.

#+BEGIN_SRC emacs-lisp
(require 'ox-latex)
(add-to-list 'org-latex-packages-alist '("cache=false" "minted"))
(setq org-latex-listings 'minted)
#+END_SRC

** Auto cleanup =latex= intermediary files
I hate all this intermediary files that =latex= creates. Just blow up all my
directories. So, I've found a solution in this [[https://emacs.stackexchange.com/questions/23982/cleanup-org-mode-export-intermediary-file][emacs stack exchange question]].

#+BEGIN_SRC emacs-lisp
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl")))
#+END_SRC

** Time tracking: Clocking
I've recently discovered this feature and is awesome. It enables time tracking
for tasks inside an agenda file.

~C-c C-x C-i~ Starts the clock on the current time
~C-c C-x C-o~ Stops the current active clock

With this option all the =CLOCKS= will be grouped into a =:CLOCKING:= entry

#+BEGIN_SRC emacs-lisp
(setq org-clock-into-drawer t)
#+END_SRC

* Packages & Tools
** =ivy=
=ivy= is a minimalistic completion engine. It supports fuzzy matching. But I
don't like this behaviour on =swiper= search engine. So, I deactivated setting
the default regexp builder with ~(swiper . ivy--regex-plus)~.

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :ensure t
  :demand t
  :delight t
  :config

  (ivy-mode) 
  (setq ivy-use-virtual-buffers t
		ivy-count-format "%d/%d ")

  (setq ivy-wrap t)

  ; Fuzzy mode
  (setq ivy-re-builders-alist
		'((swiper . ivy--regex-plus) ; No Fuzzy matchin for swiper
		  (t      . ivy--regex-fuzzy)))

  (setq ivy-initial-inputs-alist nil)

  :bind (("C-s" . swiper)
		 :map ivy-minibuffer-map
		 ("RET" . ivy-alt-done)
		 ("C-j" . ivy-next-line)
		 ("C-k" . ivy-previous-line))) 
#+END_SRC

Also, this alternative package complement =ivy=

#+BEGIN_SRC emacs-lisp
(use-package ivy-rich
  :ensure t
  :demand t
  :delight t
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
							   'ivy-rich-switch-buffer-transformer))
#+END_SRC

=counsel= is collection of Ivy-enhanced versions of common Emacs commands. So,
enhances the emacs user experience ;)

#+BEGIN_SRC emacs-lisp
(use-package counsel
  :ensure t
  :demand t
  :delight) 
#+END_SRC

=swiper= is an Ivy-enhanced alternative to isearch

#+BEGIN_SRC emacs-lisp
(use-package swiper
  :ensure t
  :demand t
  :delight)
#+END_SRC

** =flycheck=
=Flycheck= brings on-the-fly syntax checking for different languages. It comes
already with support for a lot of languages and can also use other packages as
backend.

#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :config
  (add-hook 'prog-mode-hook #'flycheck-mode)
  (set-face-underline 'flycheck-error '(:color "Red1" :style line)))
#+END_SRC

** PDF Tools
#+BEGIN_SRC emacs-lisp
(use-package pdf-tools
  :ensure t
  :config

  (pdf-tools-install))

#+END_SRC
  
There's a conflict between =evil-mode= and =pdf-view-mode=. =evil= cause that
pdf display keeps blinking. [[https://github.com/politza/pdf-tools/issues/201][xuhdev]] gives a solution to deal with this conflict.

#+BEGIN_SRC emacs-lisp
(evil-set-initial-state 'pdf-view-mode 'emacs)
(add-hook 'pdf-view-mode-hook
  (lambda ()
    (set (make-local-variable 'evil-emacs-state-cursor) (list nil))))
#+END_SRC
* Acknowledgments
- Thanks to Diego Vicente. He discovered me Emacs and =org-mode=. Also, many
  aspects of my Emacs file are inpired by his [[https://github.com/DiegoVicen/my-emacs][config file]].

* TODO-List
** TODO Format and document all the config file
** TODO Add different hooks for different mayor modes like org-mode
** TODO Configure Emacs as an IDE
*** TODO Python
*** TODO C++
*** TODO C#
